# Generated by Django 2.2.4 on 2019-09-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
