# Generated by Django 2.2.4 on 2019-09-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_element_additional_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
