# Generated by Django 2.2.4 on 2019-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='companyName',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
