# Generated by Django 2.2.4 on 2019-09-11 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extendedusers', '0002_auto_20190911_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VerificationTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extendedusers.ExtendedUser')),
            ],
        ),
    ]
