# Generated by Django 2.2.4 on 2019-09-15 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extendedusers', '0003_auto_20190911_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='companyName',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationtokens',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='extendedusers.ExtendedUser'),
        ),
    ]
